# Generated by Django 5.1.5 on 2025-01-25 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="app",
            name="user_guide",
            field=models.TextField(
                blank=True,
                help_text="Detailed instructions on how to use this application",
            ),
        ),
    ]
