# Generated by Django 5.1.5 on 2025-01-25 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0002_app_user_guide"),
    ]

    operations = [
        migrations.AddField(
            model_name="app",
            name="port",
            field=models.IntegerField(
                blank=True, help_text="Port number for web applications", null=True
            ),
        ),
    ]
