# Generated by Django 5.0 on 2025-01-25 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0003_app_port"),
    ]

    operations = [
        migrations.AddField(
            model_name="app",
            name="rating",
            field=models.IntegerField(
                blank=True,
                choices=[(1, "★"), (2, "★★"), (3, "★★★"), (4, "★★★★"), (5, "★★★★★")],
                help_text="Star rating for this application",
                null=True,
            ),
        ),
    ]
